### ISSUE TITLE
サイト内の切れている関連リンクについて

### ISSUE THREAD

**Issue by Kasugaccho** [shoma3571/-portfolio#17]
三重県コロナウイルス対策サイト（ https://github.com/shoma3571/covid19-mie/tree/Feature_shoma ）のURLが切れているようです。

また、Tavinow（ https://github.com/shoma3571/tavinow ）のURLはリポジトリが空となっているようです。

その他、Twitterリンクも存在しないアカウントになっているようです。

**Comment by shoma3571** [comment]
ありがとうございます。
また修正しておきます🙏
